### ISSUE TITLE
Use gradle to get exact version of Jenkins and plugins

### ISSUE THREAD

**Issue by samrocketman** [linagora/james-jenkins#60]
I've been exploring immutable infrastructure for Jenkins as well.  One of the primary challenges is that when installing Jenkins; it uses the latest version of all plugins.  This is not good for immutable infrastructure because if you bootstrap your Jenkins a year from now it is not guaranteed to work because it will be on different versions.

One solution I've found to this is to [use Gradle to download the WAR and exact version of all plugins](https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/build.gradle#L93).  I took it a step further and the `build.gradle` packages an RPM and a DEB package which can be used to install the immutable Jenkins.

I thought you may find it interesting so I'm opening this issue to bring your attention to it.

**Comment by mbaechler** [comment]
I guess you saw this file : https://github.com/linagora/james-jenkins/blob/master/plugins.txt
Do you mean jenkins is pulling default plugins in last version ? isn't it freezed by the jenkins version ? (our Docker file starts with `FROM jenkins:1.609.3` )

**Comment by samrocketman** [comment]
I did.  One major difference between the gradle file and your plugins.txt is you're storing binary artifacts in git.  Generally, not a recommended practice.

In the case of the gradle file, it is actually downloading from the Jenkins artifact repository at https://repo.jenkins-ci.org/ .  Another advantage of offloading to maven is the ability to cache the artifact repository using an on-site Nexus or Artifactory instance.

Just mentioning it in case you find it of interest.

**Comment by mbaechler** [comment]
I want to make it clear : the plugins we store in git are the one with patched, other ones are downloaded from the internet.

The cache thing could be interesting though, thank you very much for this discussion.
