### ISSUE TITLE
Restore stages

### ISSUE THREAD

**Issue by rouazana** [linagora/james-jenkins#86]
For building on slaves, we removed all stages to make only one.
In fact it is possible to keep stages on slaves, see https://jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#ws-allocate-workspace
We should put them back.

**Comment by mbaechler** [comment]
> In fact it is possible to keep stages on slaves, see https://jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#ws-allocate-workspace

It's latest documentation, not sure it works on our version

> We should put them back.

I'm not against that but I don't see the value it brings right now.

**Comment by rouazana** [comment]
just naming things in the workflow view

**Comment by chibenwa** [comment]
Done
